#: codeclib/internal/parsing/ConfParser.py:64
msgid ""
"Failed reading file. Please make sure to provide a file that is existent and "
"you have the permission to read it."
msgstr ""

#: codeclib/internal/process_managing/FilterProcess.py:76
msgid ""
"Unknown failure in worker process.\n"
"Exception: {}\n"
"Traceback:\n"
"{}"
msgstr ""

#: codeclib/internal/process_managing/FilterProcess.py:78
msgid ""
"An unknown failure occurred and a process is aborted. Please contact "
"developers for assistance and try out starting codec with -j1."
msgstr ""

#: codeclib/internal/process_managing/FilterProcess.py:96
msgid ""
"Failed to handle queue element {}. If you are testing filters, make sure "
"they inherit from GlobalFilter or LocalFilter and don't overwrite the kind() "
"method."
msgstr ""

#: codeclib/internal/process_managing/FilterProcess.py:99
msgid "Failed to handle queue element {}."
msgstr ""

#: codeclib/internal/process_managing/FilterProcess.py:103
msgid "Queue timeout reached. Assuming no tasks are left."
msgstr ""

#: codeclib/internal/process_managing/FilterProcess.py:116
msgid ""
"Local filter {} raised an exception of type {}. If you are the writer of "
"this filter, please catch all exceptions. If not and this error keeps "
"occurring you might want to get in contact with the writer of this filter."
msgstr ""

#: codeclib/internal/process_managing/FilterProcess.py:120
msgid "Filter {} failed to run."
msgstr ""

#. Something's gone wrong
#: codec:27
msgid "Program terminated by user."
msgstr ""
